const toggle=document.querySelector('.nav-toggle');
const nav=document.querySelector('.main-nav');
const header=document.querySelector('.site-header');
const progress=document.querySelector('.progress');
const topBtn=document.querySelector('.top');
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});
document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
window.addEventListener('scroll',()=>{const y=window.scrollY;const max=document.documentElement.scrollHeight-window.innerHeight;header?.classList.toggle('scrolled',y>10);topBtn?.classList.toggle('show',y>500);if(progress&&max>0)progress.style.width=((y/max)*100)+'%';});
topBtn?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.13});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
const cobs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=+el.dataset.count,start=performance.now();function run(now){const p=Math.min((now-start)/1100,1);el.textContent=Math.floor(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(run);else el.textContent=target}requestAnimationFrame(run);cobs.unobserve(el)}),{threshold:.5});document.querySelectorAll('[data-count]').forEach(el=>cobs.observe(el));